gcp:
  bucket:
    name: rds_log_ingestion_service

server:
  tomcat:
    threads:
      connection-timeout: 100000
#      max: 1000
#      max-connections: 3000
#    accept-count: 1000
#    max-keep-alive-requests: 1000
    keep-alive-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include:
          health,info,metrics
